apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-tarea-frontend
  namespace: aplicacion-gestion-tarea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app 
  template:
    metadata: 
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app 
          image: mgmauriciocruz/react-frontend


