apiVersion: v1
kind: Service
metadata:
  name: gestionTareaSRV-frontend
  namespace: aplicacionGestionTarea
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - name: my-app
      port: 3000
      targetPort: 3000