apiVersion: v1
kind: Service
metadata:
  name: gestion-tarea-srv-frontend
  namespace: aplicacion-gestion-tarea
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - name: my-app
      port: 3000
      targetPort: 3000