version: '3.3'
services:
 app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
